#!/bin/bash
#set -x
#DRY_RUN=1
#cpu0s=${cpu0s:-"3 7"}
cpu0s=${cpu0s:-"3 5"}
cpu1s=${cpu1s:-"17 46"}

trials=${trial:-10}

cstart=${cstart:-100}
cend=${cend:-200000}
cinc=${cinc:-2}


name=$1

if [[ -z $name ]]; then
    echo "ERROR: must specific a name for this data"
    exit -1
fi


TS=$(date +%d-%m-%y:%H:%M:%S)
datadir=data/$name/$TS
mkdir -p $datadir

(git log) >${datadir}/git.txt 2>&1
(make clean; make) >${datadir}/build.txt 2>&1
(ls -l) >${datadir}/ls.txt 2>&1
pgms=${pgms:-./bm.*}
tar -zcf ${datadir}/pgms.tgz $pgms

sudo bpftrace -e 'BEGIN { printf("%u\n", *kaddr("tsc_khz")); exit(); }' > $datadir/tsc.txt
cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq > $datadir/max_freq.txt
cat /proc/cpuinfo > $datadir/cpuinfo.txt
ifconfig > $datadir/ifconfig.txt
cp /proc/cmdline $datadir/cmdline.txt
sudo cp -r /sys/devices/system/cpu $datadir/sys-devices-system-cpu 2> /dev/null
sudo tar -czf $datadir/sys-devices-system-cpu.tgz $datadir/sys-devices-system-cpu
sudo rm -rf $datadir/sys-devices-system-cpu

for cpu in $cpu0s $cpu1s; do
    ./calibrate 1 $cpu 10 > $datadir/calibrate_${cpu}.txt 2>&1
done

for pgm in $pgms;
do
    for cpu0 in $cpu0s; do
	for cpu1 in $cpu1s; do
	    for ((i=cstart; i<cend; i=i*cinc)); do
		datafile=${datadir}/${pgm}_${i}_${cpu0}_${cpu1}.times
		echo "pgm,count,ctime,wtime,cpu0,cpu1" > $datafile
		for ((t=0; t<$trials; t++)); do
		    if [[ -n $DRY_RUN ]]; then
			echo "$pgm $i $cpu0 $cpu1 >> $datafile 2>&1"
		    else
			$pgm $i $cpu0 $cpu1 >> $datafile 2>&1
		    fi
		done 
	    done
	done
    done
done
